// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Jn7XXN7v8JISjq7CSjgV-HW3LJPvlHY',
    appId: '1:756047404797:web:5997d5447c466a13d2e894',
    messagingSenderId: '756047404797',
    projectId: 'note-flutter-app-acdd4',
    authDomain: 'note-flutter-app-acdd4.firebaseapp.com',
    storageBucket: 'note-flutter-app-acdd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cCPT2Z2VWpip_BRPCxw_xtW5wnTxT0c',
    appId: '1:756047404797:android:cbefc5b587702510d2e894',
    messagingSenderId: '756047404797',
    projectId: 'note-flutter-app-acdd4',
    storageBucket: 'note-flutter-app-acdd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGgNM56MecBUpkwBNUtclxcvlbWyTyCk',
    appId: '1:756047404797:ios:7aa10ed61284059ed2e894',
    messagingSenderId: '756047404797',
    projectId: 'note-flutter-app-acdd4',
    storageBucket: 'note-flutter-app-acdd4.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGgNM56MecBUpkwBNUtclxcvlbWyTyCk',
    appId: '1:756047404797:ios:7aa10ed61284059ed2e894',
    messagingSenderId: '756047404797',
    projectId: 'note-flutter-app-acdd4',
    storageBucket: 'note-flutter-app-acdd4.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Jn7XXN7v8JISjq7CSjgV-HW3LJPvlHY',
    appId: '1:756047404797:web:2d5da735204bf953d2e894',
    messagingSenderId: '756047404797',
    projectId: 'note-flutter-app-acdd4',
    authDomain: 'note-flutter-app-acdd4.firebaseapp.com',
    storageBucket: 'note-flutter-app-acdd4.firebasestorage.app',
  );
}
